Add `gh-team-whitelist` command line argument
cloudposse/atlantis pull request #7
Opened 2018-10-12 16:55 UTC by aknysh

## what
* Add `gh-team-whitelist` command line argument

## why
* Comma separated list of key-value pairs representing the GitHub teams and the operations that the members of a particular team is allowed to perform
* The format is {team}:{command},{team}:{command}, e.g. `dev:plan,ops:apply,devops:*`. This example means to give the users from the `dev` GitHub team the permissions to execute the `plan` command, give the `ops` team the permissions to execute the `apply` command, and allow the `devops` team to perform any operation. 
* If this argument is not provided, the default value (`*:*`) will be used and the default behavior will be to not check permissions and to allow users from any team to perform any operation

2018-10-12 17:38 UTC, osterman commented on .travis.yml
> +- make go:deps
Use `/`

2018-10-12 17:38 UTC, osterman commented on Makefile
> +go-get:
let's use `go/get`

2018-10-12 17:39 UTC, osterman commented on Makefile
> +go-build:
let's use `go/build` (e.g. like our `docker/build`)

2018-10-17 00:29 UTC, osterman commented
We've merged https://github.com/cloudposse/atlantis/pull/9 which does the same thing but uses `cloudposse/atlantis` go deps.

2019-01-07 11:32 UTC, goruha approved these changes

2019-01-07 11:32 UTC, goruha requested changes
@aknysh resolve conflicts

2019-01-07 15:27 UTC, aknysh commented
this was implemented and merged in https://github.com/cloudposse/atlantis/pull/9
closing this PR for now

2019-01-07 15:27 UTC, closed without merging

2019-07-31 00:30 UTC, Jaff commented
Will setting `ATLANTIS_GH_TEAM_WHITELIST` as environment variable behave as if I used command-line flag `--gh-team-whitelist` ?